rootProject.layout.buildDirectory.set(file("../build"))

subprojects {
    layout.buildDirectory.set(rootProject.layout.buildDirectory.dir(project.name))
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

// Suppress "source/target value 8 is obsolete" dari dependency pihak ketiga
allprojects {
    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs << "-Xlint:-options"
    }
}

// Pastikan Kotlin version konsisten
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'org.jetbrains.kotlin') {
                details.useVersion '2.2.20'
            }
        }
    }
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
